version: 2

project_name: tag

before:
  hooks:
    - go install golang.org/x/tools/cmd/stringer@latest
    - go mod tidy
    - go generate ./...
    - go fmt ./...

builds:
  - id: tag
    dir: "."
    main: "./cmd/tag"
    binary: tag
    ldflags:
      - -s -w
      - -X go.followtheprocess.codes/tag/cli.version={{.Version}}
      - -X go.followtheprocess.codes/tag/cli.commit={{.Commit}}
      - -X go.followtheprocess.codes/tag/cli.buildDate={{.Date}}
      - -X go.followtheprocess.codes/tag/cli.builtBy=GoReleaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

homebrew_casks:
  - name: tag
    binary: tag
    directory: Casks
    description: The all in one semver management tool
    homepage: https://github.com/FollowTheProcess/tag
    conflicts:
      - formula: tag
    commit_author:
      name: Tom Fleet
      email: me@followtheprocess.codes
    repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tag"]
          end

archives:
  - id: tag
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version}}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: tag
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version}}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  disable: true
