project_name: "tag"

before:
  hooks:
    - go mod tidy

builds:
  - id: "tag"
    dir: "."
    main: "./cmd/tag"
    binary: "tag"
    ldflags:
      - -s -w
      - -X github.com/FollowTheProcess/tag/cli/cmd.version={{.Version}}
      - -X github.com/FollowTheProcess/tag/cli/cmd.commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64

brews:
  - goarm: "6"
    tap:
      owner: "FollowTheProcess"
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    commit_author:
      name: "Tom Fleet"
      email: "tomfleet2018@gmail.com"
    homepage: "https://github.com/FollowTheProcess/tag"
    description: "Easy semantic versioning from the command line"
    license: "Apache Software License 2.0"
    install: |
      bin.install "tag"
    test: |
      "#{bin}/tag --version"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  # The changelog is handled by release drafter
  skip: true
