project_name: tag

before:
  hooks:
    - go install golang.org/x/tools/cmd/stringer@latest
    - go mod tidy
    - go generate ./...
    - go fmt ./...

builds:
  - id: tag
    dir: "."
    main: "./cmd/tag"
    binary: tag
    ldflags:
      - -s -w
      - -X github.com/FollowTheProcess/tag/cli.version={{.Version}}
      - -X github.com/FollowTheProcess/tag/cli.commit={{.Commit}}
      - -X github.com/FollowTheProcess/tag/cli.buildDate={{.Date}}
      - -X github.com/FollowTheProcess/tag/cli.builtBy=GoReleaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

brews:
  - repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    goarm: "7"
    directory: Formula
    commit_author:
      name: Tom Fleet
      email: tomfleet2018@gmail.com
    homepage: https://github.com/FollowTheProcess/tag
    description: The all in one semver management tool
    license: Apache Software License 2.0
    install: |
      bin.install "tag"
    test: |
      "#{bin}/tag --version"

archives:
  - id: tag
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version}}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: tag
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version}}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  disable: true
